version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: shopeasy-postgres
    environment:
      POSTGRES_DB: shopeasy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shopeasy-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: shopeasy-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_NAME: shopeasy
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: shopeasy-super-secret-key-minimum-32-characters-long
      AWS_REGION: ap-south-1
      SNS_ORDER_TOPIC_ARN: ""
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  python-service:
    build: ./python-service
    container_name: shopeasy-python
    ports:
      - "8000:8000"
    environment:
      AWS_REGION: ap-south-1
      SNS_ORDER_TOPIC_ARN: ""
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    container_name: shopeasy-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: